### ISSUE TITLE
Ticket Sales Start and End configurable per concert

### ISSUE THREAD

**Issue by elesbok** [IDAGIO/product-requirements#14]
Reason: Some concerts will be available for >24h after the live ends so we'll need to keep selling tickets for longer. Or we might want to start selling tickets at a later time, not directly with publishing the concert on the GCH.

Both **date** and **specific time** will need to be defined here.

**Comment by sdvig** [comment]
@elesbok just to make sure, this means the configuration applies only the **purchase** cta? Or **access concert** too?

**Comment by elesbok** [comment]
@sdvig it applies to all CTAs.. As long as the Ticket Purchase CTAs show, the Access Concert should also stay there. In fact, Access Concert should stay for **1 more hour after ticket sales ends** If this is too complicated to edit right now, let's keep the existing logic (which I believe hides the Purchase CTAs and the Access Concert CTA at the same time, right @davidnaas ?)

**Comment by sdvig** [comment]
@elesbok currently it is fixed 24h for the access and 23h for the sale
So the new logic will be:
- we show the **Purchase** CTA till the tickets sale end
- we show the **Access** CTA till the tickets sale end + 1h
correct?

**Comment by elesbok** [comment]
@sdvig  Can we make these fields mandatory? i.e. the event on Contentful cannot be saved without them being defined first

**Comment by elesbok** [comment]
> @elesbok currently it is fixed 24h for the access and 23h for the sale
> So the new logic will be:
> 
> * we show the **Purchase** CTA till the tickets sale end
> * we show the **Access** CTA till the tickets sale end + 1h
>   correct?

Also an update on this based on our latest convo on slack: the **Access Concert CTA** should keep showing till **availabilityEnd date & time**.
