### ISSUE TITLE
Disable dark mode on embedded web views

### ISSUE THREAD

**Issue by elesbok** [IDAGIO/product-requirements#29]
If user has chosen dark mode on web, then if the web view in the native apps will show in dark.

We'd like to disable this - embedded views are by default in light mode.

**Comment by vgidagio** [comment]
I just want to make a small correction: I believe the webview will respect the settings of the phone for dark mode. So we just need to make sure it's set to auto when embedded in the webview and this could result in either light or dakr mode depending on system settings.

**Comment by vgidagio** [comment]
Done!
